server:
  port: 8080

spring:
  profiles:
    active: del
#  main:
#    allow_circular_references: "true"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

#  datasource:
#    druid:
#      driver-class-name: ${sky.datasource.driver-class-name}
#      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: ${sky.datasource.username}
#      password: ${sky.datasource.password}

  redis:
    url: ${REDIS_URL}
#    host: ${REDIS_HOST}
#    port: 6379
#    password: ${REDIS_PASSWORD}
#    database: ${REDIS_DATABASE:10}

#    redis:
#     host: ${sky.redis.host}
#     port: ${sky.redis.port}
#     password: ${sky.redis.password}
#     database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${ALIOSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    access-key-id: ${ALIOSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET:}
    bucket-name: ${ALIOSS_BUCKET_NAME:}
#  wechat:
#    appid: ${wechat.appid}
#    secret: ${wechat.secret}
#    mchid : ${wechat.mchid}
#    mchSerialNo: ${wechat.mchSerialNo}
#    privateKeyFilePath: ${wechat.privateKeyFilePath}
#    apiV3Key: ${wechat.apiV3Key}
#    weChatPayCertFilePath: ${wechat.weChatPayCertFilePath}
#    notifyUrl: ${wechat.notifyUrl}
#    refundNotifyUrl: ${wechat.refundNotifyUrl}
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: your-ak

