server:
  port: 8080

spring:
  profiles:
    active: del
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${datasource.driver-class-name}
      url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${datasource.username}
      password: ${datasource.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${alioss.endpoint}
    access-key-id: ${alioss.access-key-id}
    access-key-secret: ${alioss.access-key-secret}
    bucket-name: ${alioss.bucket-name}
#  wechat:
#    appid: ${wechat.appid}
#    secret: ${wechat.secret}
#    mchid : ${wechat.mchid}
#    mchSerialNo: ${wechat.mchSerialNo}
#    privateKeyFilePath: ${wechat.privateKeyFilePath}
#    apiV3Key: ${wechat.apiV3Key}
#    weChatPayCertFilePath: ${wechat.weChatPayCertFilePath}
#    notifyUrl: ${wechat.notifyUrl}
#    refundNotifyUrl: ${wechat.refundNotifyUrl}
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: your-ak
